const SET_ADDRESS = 'SET_ADDRESS'
const SET_CITY = 'SET_CITY'
const SET_CRITERIA = 'SET_CRITERIA'
const SET_DESCRIPTION = 'SET_DESCRIPTION'
const SET_EMAIL = 'SET_EMAIL'
const SET_EXPENSE_RATING = 'SET_EXPENSE_RATING'
const SET_FIRST_NAME = 'SET_FIRST_NAME'
const SET_LAST_NAME = 'SET_LAST_NAME'
const SET_LOADING = 'SET_LOADING'
const SET_LOCATION = 'SET_LOCATION'
const SET_PASSWORD = 'SET_PASSWORD'
const SET_SEARCH = 'SET_SEARCH'
const SET_STATE = 'SET_STATE'
const SET_TOKEN = 'SET_TOKEN'
const SET_USER = 'SET_USER'
const SET_VISIBLE = 'SET_VISIBLE'
const SET_ZIP = 'SET_ZIP'

export default {
  SET_ADDRESS,
  SET_CITY,
  SET_CRITERIA,
  SET_DESCRIPTION,
  SET_EMAIL,
  SET_EXPENSE_RATING,
  SET_FIRST_NAME,
  SET_LAST_NAME,
  SET_LOADING,
  SET_LOCATION,
  SET_PASSWORD,
  SET_SEARCH,
  SET_STATE,
  SET_TOKEN,
  SET_USER,
  SET_VISIBLE,
  SET_ZIP,
}
